---
- hosts: all
  become: true
  vars:
  - NEWUSER: "new-user"
  - NEWUSER_PASSWORD: "{{ 'new-user-passwd' | password_hash('sha512') }}"
  tasks:
  - name: "Add user {{ NEWUSER }}"
    ansible.builtin.user:
      name: "{{ NEWUSER }}"
      generate_ssh_key: yes
      ssh_key_type: ed25519
      password: "{{ NEWUSER_PASSWORD }}"
  - name: Configure CRB
    ansible.builtin.command: dnf config-manager --set-enabled crb
  - name: Install EPEL
    ansible.builtin.dnf:
      name: epel-release
      state: present
  - name: Install packages
    ansible.builtin.dnf:
      name:
      - fail2ban
      - vim-enhanced
      - tmux
      - powerline
      - tmux-powerline
      - vim-powerline
      state: present
  - name: Modify sshd_config
    community.general.ini_file:
      path:   /etc/ssh/sshd_config
      option: "{{ item.option }}"
      value:  "{{ item.value }}"
      state:  present
    loop:
    - { option: 'PermitRootLogin', value: 'no' }
    - { option: 'PasswordAuthentication', value: 'no' }
    - { option: 'AllowUsers', value: '{{ NEWUSER }}'}
  - name: Set authorized key
    ansible.posix.authorized_key:
      user: "{{ NEWUSER }}"
      state: present
      key: ssh-algo PublicKeyStringGoesHere
...